#ifndef CPP3_BRICK_GAME_V_2_0_1_BRICK_GAME_COMMON_COMMON_DEFINES_H_
#define CPP3_BRICK_GAME_V_2_0_1_BRICK_GAME_COMMON_COMMON_DEFINES_H_

#include <string.h>

#define BOARDS_BEGIN (2)

#define BOARD_HEIGHT (20)
#define BOARD_WIDTH (10)
#define HUD_WIDTH (12)

#define DELETE (127)
#define ESCAPE (27)
#define ENTER_KEY (10)
#define PAUSE_KEY ('p')

#endif  // CPP3_BRICK_GAME_V_2_0_1_BRICK_GAME_COMMON_COMMON_DEFINES_H_