/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.2.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: controller.i

package controller

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stddef.h>
#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


extern void _wrap_Swig_free_controller_1d56a025d7372a53(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_controller_1d56a025d7372a53(swig_intgo arg1);
extern void _wrap_ControllerSnake_controller_1d56a025d7372a53(uintptr_t arg1, uintptr_t arg2);
#undef intgo
*/
import "C"

import "syscall"
import "unsafe"
import "sync"


type _ syscall.Sockaddr




type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


func getSwigcptr(v interface { Swigcptr() uintptr }) uintptr {
	if v == nil {
		return 0
	}
	return v.Swigcptr()
}


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_controller_1d56a025d7372a53(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_controller_1d56a025d7372a53(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func ControllerSnake(arg1 SignalType, arg2 Parameters) {
	_swig_i_0 := getSwigcptr(arg1)
	_swig_i_1 := getSwigcptr(arg2)
	C._wrap_ControllerSnake_controller_1d56a025d7372a53(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}


type SwigcptrParameters uintptr
type Parameters interface {
	Swigcptr() uintptr;
}
func (p SwigcptrParameters) Swigcptr() uintptr {
	return uintptr(p)
}

type SwigcptrSignalType uintptr
type SignalType interface {
	Swigcptr() uintptr;
}
func (p SwigcptrSignalType) Swigcptr() uintptr {
	return uintptr(p)
}

